### ISSUE TITLE
this no longer builds with GCC 10 it requires gcc 9.3

### ISSUE THREAD

**Issue by The-Repo-Club** [soulthreads/xwinmosaic#32]
this no longer builds with GCC 10 it requires gcc 9.3

**Comment by ZaWertun** [comment]
There is fix: https://github.com/ZaWertun/xwinmosaic/commit/82996db684db1f6642fecd5b2ef4cca5c423d0b5.

**Comment by soulthreads** [comment]
Hi, I haven't really maintained this project for more than 5 years...

@ZaWertun can you please create a pull request so I'll merge all your fixes into this repo?

**Comment by ZaWertun** [comment]
Sure, no problem.
